title: "Data Snoop"  
author: "Kirst"  
description: "Just snooping around"  
baseurl: "/data_snoop"   
url: "https://kirstinbosch.github.io"  # Change this to your repo URL  
theme: minima
paginate: 5
paginate_path: "/page:num/"

# Plugins (GitHub Pages supports these by default)  
plugins:
  - jekyll-feed  
  - jekyll-seo-tag  

# Navigation  
header_pages:
  - index.md  
  - about.md  
  - contact.md  



