title: "Data Snoop"  
author: "Kirst"  
description: "Just snooping around"  
baseurl: ""   
url: "https://kirstinbosch.github.io"  # Change this to your repo URL  

theme: cayman 
paginate: 5   

# Plugins (GitHub Pages supports these by default)  
plugins:
  - jekyll-feed  
  - jekyll-seo-tag  

# Navigation  
header_pages:
  - index.md  
  - about.md  
  - contact.md  


